### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by jeffsun905** [jasminezhoulab/cfTools#6]
Hi, 
I tried BiocManager::install("jasminezhoulab/cfTools") since the tool is not available for R4.2.2 (our system install); however I get the error of "dependency ‘cfToolsData’ is not available for package ‘cfTools’". Is there a way it can be installed without cfToolsData? Can you possibly include that in the package.
Thanks!

**Comment by RoseHuRan** [comment]
Hi,
cfToolsData is available with R 4.3 at https://bioconductor.org/packages/3.18/data/experiment/html/cfToolsData.html

If you need to install cfTools with R 4.2.2, you may try installing an older version (using the Source Package) at https://bioconductor.org/packages/3.17/bioc/html/cfTools.html
However, some functions and features are not available in the cfTools old version.

Hope it helps!
Ran

**Comment by jeffsun905** [comment]
Thank you the quick response and it is very helpful. The older version can be installed to R4.2.2.
